---
name: App-ZofCMS-Plugin-DirTreeBrowse
version: 0.0103
author:
  - "Zoffix <'zoffix@cpan.org'>"
abstract: plugin to display browseable directory tree
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  App::ZofCMS: 0.0106
  App::ZofCMS::Plugin::Base: 0.0102
  File::Glob: 1.05
  HTML::Template: 2.9
build_requires:
  Test::More: 0
provides:
  App::ZofCMS::Plugin::DirTreeBrowse:
    file: lib/App/ZofCMS/Plugin/DirTreeBrowse.pm
    version: 0.0103
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
