---
name: App-ZofCMS-Plugin-DirTreeBrowse
version: 0.0104
author:
  - "Zoffix <'zoffix@cpan.org'>"
abstract: plugin to display browseable directory tree
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
requires:
  App::ZofCMS: 0.0106
  App::ZofCMS::Plugin::Base: 0.0102
  File::Glob: 1.05
  HTML::Template: 2.9
configure_requires:
  Module::Build: 0.34
provides:
  App::ZofCMS::Plugin::DirTreeBrowse:
    file: lib/App/ZofCMS/Plugin/DirTreeBrowse.pm
    version: 0.0104
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
